### ISSUE TITLE
Datadog adds 250ms to lambda duration

### ISSUE THREAD

**Issue by Marigold** [DataDog/datadog-lambda-layer-js#53]
## Expected Behavior

I'd expect something in the `xx` ms range.

## Actual Behavior

Sending a simple metric adds ~250ms on average to execution.

## Steps to Reproduce the Problem

As simple as this

```
export const hello = datadog(async (event, context) => {
    sendDistributionMetric("custom_events.hello", 1);
    return {
      statusCode: 200,
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Credentials': true,
      },
      body: JSON.stringify({
        message: 'Go Serverless Webpack (Typescript) v1.0! Your function executed successfully!',
        input: event,
      }, null, 2),
    };
})
```

with the following serverless definition

```
hello:
    handler: handler.hello
    layers:
      - arn:aws:lambda:us-west-2:464622532012:layer:Datadog-Node10-x:17
    events:
      - http:
          method: get
          path: hello
          cors: true
```

## Specifications

  - Datadog Lambda Layer version: latest
  - Node version: 10x
